name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless


    - name: Build Angular app
      run: npm run build

    - name: SSH Deploy on Hostinger
      run: rsync -e ssh --delete-after source-path remote-user@target-server:destination-path
      with:
        source-path: ./dist/speedcar/
        target-server: ${{ secrets.IP }}
        remote-user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        public-key: ${{ secrets.PUBLIC_KEY }}
        private-ssh-key: ${{ secrets.SERVER_SSH_KEY }}
        destination-path: ~/domains/mywolf.fr/public_html/
        ssh-port: ${{ secrets.PORT }}
