name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: Run Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless
 
    - uses: actions/upload-artifact@v4
      with:
        name: artifact(build)
        path: dist/speedcar

    - name: Download artefact(build)
      uses: actions/download-artifact@v4
      with:
        name: artifact(build)

    - name: open ssh to hostinger
      run: ${{ secrets.SSHPUSHHOSTINGER }}

    - name: Ajout du mdp
      run: ${{ secrets.SSHPUSHMDP }}

    - name: Suppression du dossier existant public
      run: rm public_html

    - name: Ajout d'un dossier public vide
      run: mkdir public_html

    - name: Transfert du build
      run: mv artefact(build) public_html

