name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: List files in directory
      run: ls -la

    - name: Run Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless
      
    - name: upload artefctbuild
      uses: actions/upload-artifact@v4
      with:
        name: artifactbuild
        path: ./dist

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: artifactbuild
        path: ./dist

    - name: Deploy project with SSH
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PASSWORD }}
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        SOURCE: "./dist"
        TARGET: "domains/mywolf.fr/public_html"


