name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build

    - name: List files in directory
      run: ls -la

    - name: Run Tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless
      
    - name: upload artefctbuild
      uses: actions/upload-artifact@v4
      with:
        name: artifactbuild
        path: ./dist

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: artifactbuild
        path: ./dist

    - name: rsync deployment to remote hostinger
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        rsh: ${{ secrets.SSHPUSHHOSTINGER }}
        path: ./dist
        remote_path: domains/mywolf.fr/public_html
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.PORT }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key_pass: ${{ secrets.PASSWORD }}
