on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: Deploy to Hostinger
      uses: easingthemes/ssh-deploy@v2.1.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.IP }}
        REMOTE_PORT: ${{ secrets.PORT }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/.git, /.github, /dist/, /node_modules/"
